defaults:
  n_eval_episodes: 3
  eval_every_n_steps: 500_000
  console_log_freq: 1 # in episodes
  reward_window_size: 100
  seed: 42
  deterministic: false

PongNoFrameskip-v4:
  max_steps: 20_000_000
  mean_reward_bound: 18
  gamma: 0.99
  learning_rate: 1.0e-3
  batch_size: 128
  episode_limit_steps: 500
  reward_steps: 4
  entropy_beta: 0.01
  n_envs: 50
  grad_l2_clip: 0.1

  eval_every_n_steps: 200_000
