defaults:
  n_eval_episodes: 3
  eval_every_n_steps: 50_000
  console_log_freq: 50 # in episodes
  reward_window_size: 100
  seed: 42
  deterministic: false

CartPole-v1:
  max_steps: 1_000_000
  mean_reward_bound: 195
  gamma: 0.99
  learning_rate: 1.0e-3
  episodes_to_train: 6
  episode_limit_steps: 200
