defaults:
  n_eval_episodes: 3
  eval_every_n_steps: 50_000
  console_log_freq: 50 # in episodes
  reward_window_size: 100
  seed: 42
  deterministic: false

CartPole-v1:
  max_steps: 1_000_000
  mean_reward_bound: 195
  gamma: 0.99
  learning_rate: 5.0e-4
  batch_size: 8
  episode_limit_steps: 200
  reward_steps: 10
  entropy_beta: 0.01

PongNoFrameskip-v4:
  max_steps: 1_000_000
  mean_reward_bound: 20
  gamma: 0.99
  learning_rate: 1.0e-4
  batch_size: 128
  episode_limit_steps: 200
  reward_steps: 10
  entropy_beta: 0.01
  n_envs: 32
  baseline_steps: 1_000_000
  grad_l2_clip: 0.1
  reward_window_size: 50
